### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by ssdhaliwal** [DoDGOSS/ozone#6]
ozone-framework-client - build works

ozone-example-widgets- fail; 

E:\ozone-8.0.0.0.0-GA>cd ozone-example-widgets/

E:\ozone-8.0.0.0.0-GA\ozone-example-widgets>npm install
npm WARN deprecated core-js@2.6.5: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependenci
es to the actual version of core-js@3.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependenc
ies to the actual version of core-js@3.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependenci
es to the actual version of core-js@3.

> node-sass@4.11.0 install E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-72_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.11.0 postinstall E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\node-sass
> node scripts/build.js

Building: D:\Programs\nodejs\node.exe E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsa
ss_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'D:\\Programs\\nodejs\\node.exe',
gyp verb cli   'E:\\ozone-8.0.0.0.0-GA\\ozone-example-widgets\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.14.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (E:\\ozone-8.0.0.0.0-GA\\ozone-example-widgets\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (E:\\ozone-8.0.0.0.0-GA\\ozone-example-widgets\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (E:\\ozone-8.0.0.0.0-GA\\ozone-example-widgets\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at E:\\ozone-8.0.0.0.0-GA\\ozone-example-widgets\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at E:\\ozone-8.0.0.0.0-GA\\ozone-example-widgets\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at E:\\ozone-8.0.0.0.0-GA\\ozone-example-widgets\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Program Files\Python37\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:295:12)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "D:\\Programs\\nodejs\\node.exe" "E:\\ozone-8.0.0.0.0-GA\\ozone-example-widgets\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose
" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\node-sass
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.1 (node_modules\fsevents\node_modules\abbrev):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\abbrev' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.abbrev.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ansi-regex@2.1.1 (node_modules\fsevents\node_modules\ansi-regex):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\ansi-regex' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.ansi-regex.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: aproba@1.2.0 (node_modules\fsevents\node_modules\aproba):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\aproba' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.aproba.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: balanced-match@1.0.0 (node_modules\fsevents\node_modules\balanced-match):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\balanced-match' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.balanced-match.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chownr@1.1.3 (node_modules\fsevents\node_modules\chownr):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\chownr' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.chownr.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: code-point-at@1.1.0 (node_modules\fsevents\node_modules\code-point-at):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\code-point-at' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.code-point-at.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: concat-map@0.0.1 (node_modules\fsevents\node_modules\concat-map):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\concat-map' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.concat-map.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: console-control-strings@1.1.0 (node_modules\fsevents\node_modules\console-control-strings):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\console-control-strings' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.console-control-strings.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-util-is@1.0.2 (node_modules\fsevents\node_modules\core-util-is):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\core-util-is' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.core-util-is.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: deep-extend@0.6.0 (node_modules\fsevents\node_modules\deep-extend):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\deep-extend' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.deep-extend.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: delegates@1.0.0 (node_modules\fsevents\node_modules\delegates):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\delegates' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.delegates.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: detect-libc@1.0.3 (node_modules\fsevents\node_modules\detect-libc):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\detect-libc' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.detect-libc.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs.realpath@1.0.0 (node_modules\fsevents\node_modules\fs.realpath):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\fs.realpath' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.fs.realpath.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: has-unicode@2.0.1 (node_modules\fsevents\node_modules\has-unicode):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\has-unicode' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.has-unicode.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: inherits@2.0.4 (node_modules\fsevents\node_modules\inherits):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\inherits' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.inherits.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ini@1.3.5 (node_modules\fsevents\node_modules\ini):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\ini' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.ini.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: isarray@1.0.0 (node_modules\fsevents\node_modules\isarray):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\isarray' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.isarray.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@0.0.8 (node_modules\fsevents\node_modules\minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\minimist' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ms@2.1.2 (node_modules\fsevents\node_modules\ms):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\ms' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.ms.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: npm-normalize-package-bin@1.0.1 (node_modules\fsevents\node_modules\npm-normalize-package-bin):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\npm-normalize-package-bin' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.npm-normalize-package-bin.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: number-is-nan@1.0.1 (node_modules\fsevents\node_modules\number-is-nan):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\number-is-nan' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.number-is-nan.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: object-assign@4.1.1 (node_modules\fsevents\node_modules\object-assign):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\object-assign' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.object-assign.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-homedir@1.0.2 (node_modules\fsevents\node_modules\os-homedir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\os-homedir' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.os-homedir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-tmpdir@1.0.2 (node_modules\fsevents\node_modules\os-tmpdir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\os-tmpdir' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.os-tmpdir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: path-is-absolute@1.0.1 (node_modules\fsevents\node_modules\path-is-absolute):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\path-is-absolute' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.path-is-absolute.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: process-nextick-args@2.0.1 (node_modules\fsevents\node_modules\process-nextick-args):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\process-nextick-args' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.process-nextick-args.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@1.2.0 (node_modules\fsevents\node_modules\rc\node_modules\minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\rc\node_modules\minimist' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\rc\node_modules\.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safe-buffer@5.1.2 (node_modules\fsevents\node_modules\safe-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\safe-buffer' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.safe-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safer-buffer@2.1.2 (node_modules\fsevents\node_modules\safer-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\safer-buffer' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.safer-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sax@1.2.4 (node_modules\fsevents\node_modules\sax):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\sax' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.sax.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: semver@5.7.1 (node_modules\fsevents\node_modules\semver):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\semver' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.semver.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: set-blocking@2.0.0 (node_modules\fsevents\node_modules\set-blocking):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\set-blocking' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.set-blocking.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: signal-exit@3.0.2 (node_modules\fsevents\node_modules\signal-exit):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\signal-exit' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.signal-exit.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strip-json-comments@2.0.1 (node_modules\fsevents\node_modules\strip-json-comments):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\strip-json-comments' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.strip-json-comments.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: util-deprecate@1.0.2 (node_modules\fsevents\node_modules\util-deprecate):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\util-deprecate' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.util-deprecate.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wrappy@1.0.2 (node_modules\fsevents\node_modules\wrappy):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\wrappy' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.wrappy.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yallist@3.1.1 (node_modules\fsevents\node_modules\yallist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_
modules\yallist' -> 'E:\ozone-8.0.0.0.0-GA\ozone-example-widgets\node_modules\fsevents\node_modules\.yallist.DELETE'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2020-03-15T15_19_34_244Z-debug.log
[2020-03-15T15_19_34_244Z-debug.log](https://github.com/DoDGOSS/ozone/files/4334396/2020-03-15T15_19_34_244Z-debug.log)

**Comment by ryan-WORK** [comment]
Hi @ssdhaliwal, what are the versions of `npm` and `node` are you running?
